### ISSUE TITLE
[Query] Reason for using Rust Over Go or C

### ISSUE THREAD

**Issue by Hakai-Shin** [kixelated/moq-rs#64]
I am a newbie to media domain. I am curious about switching this project from golang to rust and why c/c++ was not considered.

**Comment by kixelated** [comment]
Of course!

I've spent the last ~10 years working on Go. If you go far back enough, you'll find this server [used to be written in Go](https://github.com/kixelated/moq-rs/commit/2601c40b54ec0e40c7651a4e870e1f3f65854fbe). I switched because:

1. Rust is much better for integrating with C++ projects like OBS and ffmpeg. `cgo` exists but it's slow and painful.
2. The QUIC library quic-go is okay, but lacks functionality. We absolutely need [BBR support](https://github.com/quic-go/quic-go/issues/341#issuecomment-1296282730) and [stream prioritization](https://github.com/quic-go/quic-go/pull/3442#issuecomment-1150853814). Meanwhile there are multiple good QUIC libraries written in Rust.
3. Rust is more fun and an opportunity to grow.

I've done some C++ in the past, including working on the transcoder and video player (lul) at Twitch. The language is very poor for concurrency it's too easy to make critical mistakes at runtime. There are absolutely C++ experts who have learned how to not shoot themselves in the foot, but the Rust compiler makes you avoid those mistakes in the first place.

Rust is also just a nice and modern language; you should try it.

**Comment by Hakai-Shin** [comment]
Yeah, i saw that commit and since the commit message didnt have much details i posted this query. I do hear a lot of buzz around rust. Thanks for your quick and helpful response.

**Comment by Hakai-Shin** [comment]
Yeah, i saw that commit and since the commit message didnt have much details i posted this query. I do hear a lot of buzz around rust. Thanks for your quick and helpful response.
